package coreJavaTraining;

public class ExceptionDemo {

	public static void main(String[] args) throws Exception {
		// TODO Auto-generated method stub
		int a = 4;
		int b = 0;
		int arr[]= {1,2,3};
		
		try
		{
		//	int c=a/b;
		// 	System.out.println(c);
			System.out.println(arr[89]);
		}
			
	
		
		finally
		{
			System.out.println("Always Excuted");
			
		}

	}

	
}
